### ISSUE TITLE
Support for 6.0

### ISSUE THREAD

**Issue by Rykaerdoe** [Regateiro/ATBCrafter#1]
Hello. Is the project still being updated? Will there be an update to 6.0? New skills were introduced and since ATBCrafter checks the name of the skills cast, one cannot use the newer skills with it. Thanks!

**Comment by Regateiro** [comment]
Hi. Yes it will be updated sometime during next week. In the meantime if you want to use it I believe you may add them to the configuration file, following the other skills examples.
